model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "pragmatic"
approval_policy = "on-failure"

[features]
shell_tool = false

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[mcp_servers.context7]
command = "pnpm"
args = ["dlx", "@upstash/context7-mcp@latest"]
startup_timeout_ms = 20_000


[mcp_servers.desktop-commander]
enabled = true
command = "pnpm"
args = ["dlx", "@wonderwhy-er/desktop-commander@latest"]
env = { PYTHONUTF8 = "1" }

[mcp_servers.desktop-commander.tools.start_process]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.edit_block]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.set_config_value]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.interact_with_process]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.move_file]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.kill_process]
approval_mode = "approve"

[mcp_servers.desktop-commander.tools.create_directory]
approval_mode = "approve"



[projects.'C:\Users\AA\.codex']
trust_level = "trusted"


[projects.'E:\dev\py\alchemy-dev']
trust_level = "trusted"

[apps.connector_76869538009648d5b282a4bb21c3d157.tools.github_update_file]
approval_mode = "approve"

[marketplaces.openai-bundled]
last_updated = "2026-05-09T09:54:27Z"
source_type = "local"
source = '\\?\C:\Users\AA\.codex\.tmp\bundled-marketplaces\openai-bundled'
